### ISSUE TITLE
Here's a Slack "App Manifest" to make adding the user token scopes easier

### ISSUE THREAD

**Issue by Efresia** [sgratzl/slack_cleaner2#89]
Thank you for this fantastic tool. Here's an "App Manifest" template can be pasted into the app manifest section of the slack UI, just change the name to match the name you used when you created the "app". The duplicate scopes are commented out so it works as-is. You can of course paste just a section as well.

```
display_information:
  name: slack_cleaner
oauth_config:
  scopes:
    user:
      # General channel and user detection
      - users:read
      - channels:read
      - groups:read
      - im:read
      - mpim:read
      # Deleting messages from public channels
      #- users:read
      #- channels:read
      - channels:history
      - chat:write
      # Deleting messages from private channels
      #- users:read
      #- groups:read
      - groups:history
      #- chat:write
      # Deleting messages from 1:1 IMs
      #- im:read
      - im:history
      #- users:read
      #- chat:write
      # Deleting messages from multi-person IMs
      #- mpim:read
      - mpim:history
      #- users:read
      #- chat:write
      # Deleting files
      - files:read
      #- users:read
      - files:write
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
```
